name: Daily-RSS-Processing

on:
  schedule:
    - cron: '0 12 * * *'  # Runs every day at 12:00 UTC
  workflow_dispatch:

permissions:
  contents: write  # ✅ Needed to allow git push via GITHUB_TOKEN

jobs:
  rss-to-wix:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Ensure data folder exists and is tracked
        run: |
          mkdir -p data
          touch data/.gitkeep
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add data/.gitkeep
          git commit -m "Ensure data folder is tracked" || echo "Nothing to commit"

      - name: Run RSS Feed Script
        run: python main.py

      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"

          # ✅ Set remote to use GitHub token for authenticated push
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}

          git add -A
          git commit -m "Automated update from RSS script" || echo "No changes to commit"
          git push origin HEAD
